### ISSUE TITLE
HDMI?

### ISSUE THREAD

**Issue by jgilcas** [lfantoniosi/tn9k_f18a#1]
Good afternoon.

Congratulations for the work done. I have a doubt, the vga breakout is optional, I understand then that the output is hdmi if the vga breakout is not used?

Regards.

**Comment by lfantoniosi** [comment]
No, HDMI is always there. You can have HDMI with and without VGA breaker. Look my video I output both at same time.

**Comment by lfantoniosi** [comment]
it was a question
