### ISSUE TITLE
GoWin IDE Version

### ISSUE THREAD

**Issue by Archimedes5000** [lfantoniosi/tn9k_f18a#3]
Hi, you wrote: "You must use the version 1.9.8.10 of the Gowin IDE and programmer". There is a new version online: 1.9.8.11. Does it work ? I think so. I would like to suggest changing the statement to the minimal version.

Greetings Axel

**Comment by hanshuebner** [comment]
I can confirm that 1.9.8.11 works fine.

**Comment by lfantoniosi** [comment]
I tested on Education as well and it is working Someone had reported it did not worked on the latest beta.

**Comment by lfantoniosi** [comment]
I have updated the readme
